---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r}
library(knitr)
setwd("~/Desktop/coursera/Reproducible Research/Course Project 1")
aa<- read.csv("activity.csv")
aa$date<- as.Date(aa$date)
```

## What is mean total number of steps taken per day?
```{r}
bb<- sapply(split(aa$steps, aa$date), sum, na.rm = TRUE)
print(bb)
```

```{r}
hist(bb, xlab = "number of steps", main = "Total number of steps taken per day")
```
```{r}
mean(bb)
median(bb)
```
## What is the average daily activity pattern?
```{r}
cc<- as.data.frame(sapply(split(aa$steps, aa$interval), mean, na.rm = TRUE))
colnames(cc) <- "steps"
cc$intervals<- aa[1:288, 3]
library(ggplot2)
g<- ggplot(cc, aes(intervals, steps))
g + geom_point() + geom_line()
```
```{r}
subset(cc, cc$steps == max(cc$steps))
```
## Imputing missing values
```{r}
sum(is.na(aa$steps))
```
```{r}
for(i in 1:nrow(aa)){
  if(is.na(aa[i, 1])){
    aa[i, 1]<- cc[cc$intervals == aa[i, 3], ]$steps
  }
}
newdataset<- aa
```
```{r}
dd<- sapply(split(newdataset$steps, newdataset$date), sum, na.rm = TRUE)
hist(bb, xlab = "number of steps", main = "Total number of steps taken per day")
```
```{r}
mean(dd)
median(dd)
```
## Are there differences in activity patterns between weekdays and weekends?
```{r}
newdataset$date<- as.Date(newdataset$date)
newdataset$days<- weekdays(newdataset$date)
for(i in 1:nrow(newdataset)){
 if (newdataset[i, 4] %in% c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday")){
    newdataset[i, 4]<- "weekday"
  } else {newdataset[i, 4]<- "weekend"}
}
newdataset$days<- as.factor(newdataset$days)
head(newdataset)
```
```{r}
ee<- split(newdataset, newdataset$days)
ff<- lapply(ee, function(x) with(x, tapply(steps, interval, mean)))
ff<- as.data.frame(ff)
colnames(ff)<- c("weekday", "weekend")
library(tidyr)
ff<- ff %>% gather(days, steps, "weekday", "weekend")
ff$intervals<- cc$intervals
g<- ggplot(ff, aes(intervals, steps, color = days))
g + geom_point()+ geom_line()
```
